### PR TITLE
[WIP] Add Settings component

### PR DESCRIPTION
**Pull request by karatakis**
selection_031

### CODE REVIEW

**Comment by karatakis** [comment]
It is just the UI, we can wire the settings to a global store, so every component can access the settings.

**Comment by rafaelleru** [comment]
Yeah it's a good first aproach and yes we will put the settings in a store, you can go ahead if you like, but I was thinking in a whole page for setings instead of a popup, can you make a complete page and display it when the button is clicked?¿

**Comment by karatakis** [comment]
I can work on that tommorow, and I will try to create a Vuex store along with it

**Comment by rafaelleru** [comment]
ok, thanks 😸

**Comment by karatakis** [comment]
I will use vue-router to implement the transition to different pages, is there any way to perform routing in electron ?

**Comment by karatakis** [comment]
After I added the vue-router, The electron hot reloading makes the application not to render correctly. I don't know what I messed up :cry: 
selection_001
It shows perfectly the dom nodes, but the screen is white.

**Comment by rafaelleru** [comment]
Really, it is so weird. Do you have any other instanceof torrent player running?

**Comment by rafaelleru** [comment]
Are you still working on this? @karatakis

**Comment by karatakis** [comment]
I am working this during weekends.
Are you planing to use Vue-router in the future ?

**Comment by rafaelleru** [comment]
Yes, I was looking and vue-router seems to be what we need. 😀

**Pull request closed without merging**
